# Generated by Django 3.1.6 on 2021-02-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='creator',
        ),
    ]
