# Generated by Django 3.1.6 on 2021-02-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20210212_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='creator',
        ),
    ]
